// This file is auto-generated by Supabase CLI
// Run: npm run db:generate-types
// After setting up your Supabase project and running migrations

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string | null
          phone: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          phone?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          phone?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      households: {
        Row: {
          id: string
          name: string
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      household_members: {
        Row: {
          household_id: string
          user_id: string
          member_role: string
          created_at: string
        }
        Insert: {
          household_id: string
          user_id: string
          member_role?: string
          created_at?: string
        }
        Update: {
          household_id?: string
          user_id?: string
          member_role?: string
          created_at?: string
        }
      }
      children: {
        Row: {
          id: string
          household_id: string
          first_name: string
          last_name: string | null
          date_of_birth: string | null
          photo_url: string | null
          allergies: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          household_id: string
          first_name: string
          last_name?: string | null
          date_of_birth?: string | null
          photo_url?: string | null
          allergies?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          household_id?: string
          first_name?: string
          last_name?: string | null
          date_of_birth?: string | null
          photo_url?: string | null
          allergies?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      rooms: {
        Row: {
          id: string
          name: string
          min_age_months: number | null
          max_age_months: number | null
          capacity: number | null
          active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          min_age_months?: number | null
          max_age_months?: number | null
          capacity?: number | null
          active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          min_age_months?: number | null
          max_age_months?: number | null
          capacity?: number | null
          active?: boolean
          created_at?: string
        }
      }
      services: {
        Row: {
          id: string
          title: string
          starts_at: string
          ends_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          title: string
          starts_at: string
          ends_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          title?: string
          starts_at?: string
          ends_at?: string | null
          created_at?: string
        }
      }
      checkins: {
        Row: {
          id: string
          service_id: string
          child_id: string
          room_id: string
          checked_in_at: string
          checked_out_at: string | null
          checked_in_by: string
          checked_out_by: string | null
          status: string
          pickup_token: string | null
          created_at: string
        }
        Insert: {
          id?: string
          service_id: string
          child_id: string
          room_id: string
          checked_in_at?: string
          checked_out_at?: string | null
          checked_in_by: string
          checked_out_by?: string | null
          status?: string
          pickup_token?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          service_id?: string
          child_id?: string
          room_id?: string
          checked_in_at?: string
          checked_out_at?: string | null
          checked_in_by?: string
          checked_out_by?: string | null
          status?: string
          pickup_token?: string | null
          created_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          checkin_id: string
          room_id: string
          type: string
          message: string | null
          created_by: string
          created_at: string
          acknowledged_at: string | null
          acknowledged_by: string | null
          resolved_at: string | null
          resolved_by: string | null
          status: string
        }
        Insert: {
          id?: string
          checkin_id: string
          room_id: string
          type?: string
          message?: string | null
          created_by: string
          created_at?: string
          acknowledged_at?: string | null
          acknowledged_by?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string
        }
        Update: {
          id?: string
          checkin_id?: string
          room_id?: string
          type?: string
          message?: string | null
          created_by?: string
          created_at?: string
          acknowledged_at?: string | null
          acknowledged_by?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string
        }
      }
      user_roles: {
        Row: {
          user_id: string
          role: string
          granted_by: string | null
          created_at: string
        }
        Insert: {
          user_id: string
          role: string
          granted_by?: string | null
          created_at?: string
        }
        Update: {
          user_id?: string
          role?: string
          granted_by?: string | null
          created_at?: string
        }
      }
      audit_log: {
        Row: {
          id: string
          actor_id: string | null
          action: string
          entity_type: string | null
          entity_id: string | null
          meta: Json
          created_at: string
        }
        Insert: {
          id?: string
          actor_id?: string | null
          action: string
          entity_type?: string | null
          entity_id?: string | null
          meta?: Json
          created_at?: string
        }
        Update: {
          id?: string
          actor_id?: string | null
          action?: string
          entity_type?: string | null
          entity_id?: string | null
          meta?: Json
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      has_role: {
        Args: {
          role_name: string
        }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
