/**
 * "Our Values" — the Church's own statement of faith, carried over from the
 * About page of newheightschurch.info word for word (punctuation normalized).
 * These were written by the house; do not paraphrase, reorder, or trim.
 * Rendered on /about/beliefs by `ValuesList`.
 */

export interface Value {
  key: string;
  title: string;
  /** One or more paragraphs, verbatim. */
  text: readonly string[];
}

export const PURPOSE = {
  headline: "To love people and point them to Christ.",
  you: "God puts a premium on people. So do we. You and your family are important to us and we look forward to serving you soon!",
  us: "New Heights has a clear vision: to love people and point them to Christ. Join us and help reach the community of Bryan/College Station!",
} as const;

export const VALUES: readonly Value[] = [
  {
    key: "bible",
    title: "The Holy Bible",
    text: [
      "The Holy Bible, and only the Bible, is the authoritative Word of God. It alone is the final authority in determining all doctrinal truths. In its original writing, it is inspired, infallible and inerrant.",
    ],
  },
  {
    key: "trinity",
    title: "Trinity",
    text: [
      "There is one God, eternally existent in three persons: Father, Son and Holy Spirit. These three are coequal and co-eternal.",
    ],
  },
  {
    key: "jesus",
    title: "Jesus Christ",
    text: [
      "Jesus Christ is God the Son, the second person of the Trinity. On earth, Jesus was 100% God and 100% man. He is the only man ever to have lived a sinless life.",
    ],
  },
  {
    key: "virgin-birth",
    title: "Virgin Birth",
    text: [
      "Jesus Christ was conceived by God the Father, through the Holy Spirit in the virgin Mary's womb; therefore, He is the Son of God.",
    ],
  },
  {
    key: "redemption",
    title: "Redemption",
    text: [
      "Man was created good and upright, but by voluntary transgression he fell; his only hope of redemption is in Jesus Christ, the Son of God.",
    ],
  },
  {
    key: "regeneration",
    title: "Regeneration",
    text: [
      "For anyone to know God, regeneration by the Holy Spirit is absolutely essential.",
    ],
  },
  {
    key: "salvation",
    title: "Salvation",
    text: [
      "We are saved by grace through faith in Jesus Christ; His death, burial, and resurrection. Salvation is a gift from God, not a result of our good works.",
    ],
  },
  {
    key: "repentance",
    title: "Repentance",
    text: [
      "Repentance is the commitment to turn away from sin in every area of our lives and to follow Christ, which allows us to receive His redemption and to be regenerated by the Holy Spirit.",
    ],
  },
  {
    key: "sanctification",
    title: "Sanctification",
    text: [
      "Sanctification is the ongoing process of yielding to God's Word and His Spirit in order to complete the development of Christ's character in us.",
    ],
  },
  {
    key: "blood",
    title: "Jesus' Blood",
    text: [
      "The Blood that Jesus Christ shed on the Cross of Calvary was sinless and is 100% sufficient to cleanse mankind of all sin.",
    ],
  },
  {
    key: "indwells",
    title: "Jesus Christ Indwells All Believers",
    text: [
      "Christians are people who have invited the Lord Jesus Christ to come and live inside them by His Holy Spirit.",
    ],
  },
  {
    key: "baptism-spirit",
    title: "Baptism in the Holy Spirit",
    text: [
      "Given at Pentecost, it is the promise of the Father, sent by Jesus after His Ascension, to empower the Church to preach the Gospel throughout the whole earth.",
    ],
  },
  {
    key: "gifts",
    title: "The Gifts of the Holy Spirit",
    text: [
      "The Holy Spirit is manifested through a variety of spiritual gifts to build and sanctify the church, demonstrate the validity of the resurrection, and confirm the power of the Gospel.",
    ],
  },
  {
    key: "church",
    title: "The Church",
    text: [
      "The church is the Body of Christ, the habitation of God through the Spirit, with divine appointments for the fulfillment of Jesus' Great Commission.",
    ],
  },
  {
    key: "sacraments",
    title: "The Two Sacraments",
    text: [
      "Water Baptism: Following faith in the Lord Jesus Christ, the new convert is commanded by the Word of God to be baptized in water in the Name of the Father and of the Son and of the Holy Spirit (Matthew 28:19; Acts 2:38; Mark 16:16; Acts 8:12, 36–38; 10:47–48).",
      "The Lord's Supper: A unique time of communion in the presence of God when the elements of bread and grape juice (the Body and Blood of the Lord Jesus Christ) are taken in remembrance of Jesus' sacrifice on the Cross (Matthew 26:26–29; I Corinthians 10:16, 11:23–25).",
    ],
  },
  {
    key: "healing",
    title: "Healing of the Sick",
    text: [
      "Healing of the sick is illustrated in the life and ministry of Jesus, and included in the commission of Jesus to His disciples.",
    ],
  },
  {
    key: "provision",
    title: "God's Will for Provision",
    text: [
      "It is the Father's will for believers to become whole, healthy and successful in all areas of life.",
    ],
  },
  {
    key: "resurrection",
    title: "Resurrection",
    text: [
      "Jesus Christ was physically resurrected from the dead in a glorified body three days after His death on the cross.",
    ],
  },
  {
    key: "heaven",
    title: "Heaven",
    text: [
      "Heaven is the eternal dwelling place for all believers in the Gospel of Jesus Christ.",
    ],
  },
  {
    key: "hell",
    title: "Hell",
    text: [
      "After living one life on earth, the unbelievers will be judged by God and sent to Hell where they will be eternally tormented.",
    ],
  },
  {
    key: "second-coming",
    title: "Second Coming",
    text: [
      "Jesus Christ will physically and visibly return to earth for the second time to establish His Kingdom.",
    ],
  },
];
