"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { BookOpen, ChevronLeft } from "lucide-react";

const beliefs = [
  {
    title: "The Holy Bible",
    content: "The Holy Bible, and only the Bible, is the authoritative Word of God. It alone is the final authority in determining all doctrinal truths. In its original writing, it is inspired, infallible and inerrant.",
    scripture: "II Timothy 3:16; II Peter 1:20-21; Proverbs 30:5; Romans 16:25-26"
  },
  {
    title: "Trinity",
    content: "There is one God, eternally existent in three persons: Father, Son and Holy Spirit. These three are coequal and co-eternal.",
    scripture: "I John 5:7; Genesis 1:26; Matthew 3:16-17, 28:19; Luke 1:35; Isaiah 9:6; Hebrews 3:7-11"
  },
  {
    title: "Jesus Christ",
    content: "Jesus Christ is God the Son, the second person of the Trinity. On earth, Jesus was 100% God and 100% man. He is the only man ever to have lived a sinless life. He was born of a virgin, lived a sinless life, performed miracles, died on the cross for mankind and thus, atoned for our sins through the shedding of His blood. He rose from the dead on the third day according to the Scriptures, ascended to the right hand of the Father, and will return again in power and glory.",
    scripture: "John 1:1,14, 20:28; I Timothy 3:16; Isaiah 9:6; Philippians 2:5-6; I Timothy 2:5"
  },
  {
    title: "Virgin Birth",
    content: "Jesus Christ was conceived by God the Father, through the Holy Spirit (the third person of the Trinity) in the virgin Mary's womb; therefore, He is the Son of God.",
    scripture: "Matthew 1:18, 25; Luke 1:35; Isaiah 7:14; Luke 1:27-35"
  },
  {
    title: "Redemption",
    content: "Man was created good and upright, but by voluntary transgression he fell; his only hope of redemption is in Jesus Christ, the Son of God.",
    scripture: "Genesis 1:26-31, 3:1-7; Romans 5:12-21"
  },
  {
    title: "Regeneration",
    content: "For anyone to know God, regeneration by the Holy Spirit is absolutely essential.",
    scripture: "John 6:44, 65; Matthew 19:28; Titus 3:5"
  },
  {
    title: "Salvation",
    content: "We are saved by grace through faith in Jesus Christ; His death, burial, and resurrection. Salvation is a gift from God, not a result of our good works or of any human efforts.",
    scripture: "Ephesians 2:8-9; Galatians 2:16, 3:8; Titus 3:5; Romans 10:9-10; Acts 16:31; Hebrews 9:22"
  },
  {
    title: "Repentance",
    content: "Repentance is the commitment to turn away from sin in every area of our lives and to follow Christ, which allows us to receive His redemption and to be regenerated by the Holy Spirit. Thus, through repentance we receive forgiveness of sins and appropriate salvation.",
    scripture: "Acts 2:21, 3:19; I John 1:9"
  },
  {
    title: "Sanctification",
    content: "Sanctification is the ongoing process of yielding to God's Word and His Spirit in order to complete the development of Christ's character in us. It is through the present ministry of the Holy Spirit and the Word of God that the Christian is enabled to live a Godly life.",
    scripture: "I Thessalonians 4:3, 5:23; II Corinthians 3:18, 6:14-18; II Thessalonians 2:1-3; Romans 8:29, 12:1-2; Hebrews 2:11"
  },
  {
    title: "Jesus' Blood",
    content: "The Blood that Jesus Christ shed on the Cross of Calvary was sinless and is 100% sufficient to cleanse mankind of all sin. Jesus allowed Himself to be punished for both our sinfulness and our sins, enabling all those who believe to be free from the penalty of sin, which is death.",
    scripture: "I John 1:7; Revelation 1:5, 5:9; Colossians 1:20; Romans 3:10-12, 23, 5:9; John 1:29"
  },
  {
    title: "Jesus Christ Indwells All Believers",
    content: "Christians are people who have invited the Lord Jesus Christ to come and live inside them by His Holy Spirit. They relinquish the authority of their lives over to him thus making Jesus the Lord of their life as well as Savior. They put their trust in what Jesus accomplished for them when He died, was buried, and rose again from the dead.",
    scripture: "John 1:12; John 14:17, 23; John 15:4; Romans 8:11; Revelation 3:20"
  },
  {
    title: "Baptism In the Holy Spirit",
    content: "Given at Pentecost, it is the promise of the Father, sent by Jesus after His Ascension, to empower the Church to preach the Gospel throughout the whole earth.",
    scripture: "Joel 2:28-29; Matthew 3:11; Mark 16:17; Acts 1:5, 2:1-4, 17, 38-39, 8:14-17, 10:38, 44-47, 11:15-17, 19:1-6"
  },
  {
    title: "The Gifts of the Holy Spirit",
    content: "The Holy Spirit is manifested through a variety of spiritual gifts to build and sanctify the church, demonstrate the validity of the resurrection, and confirm the power of the Gospel. The Bible lists of these gifts are not necessarily exhaustive, and the gifts may occur in various combinations. All believers are commanded to earnestly desire the manifestation of the gifts in their lives. These gifts always operate in harmony with the Scriptures and should never be used in violation of Biblical parameters.",
    scripture: "Hebrews 2:4; Romans 1:11, 12:4-8; Ephesians 4:16; I Timothy 4:14; II Timothy 1:6-7; I Corinthians 12:1-31, 14:1-40; I Peter 4:10"
  },
  {
    title: "The Church",
    content: "The church is the Body of Christ, the habitation of God through the Spirit, with divine appointments for the fulfillment of Jesus' Great Commission. Every person who is born of the Spirit is an integral part of the church as a member of the body of believers. There is a spiritual unity of all believers in our Lord Jesus Christ.",
    scripture: "Ephesians 1:22, 2:19-22; Hebrews 12:23; John 17:11, 20-23"
  },
  {
    title: "Water Baptism",
    content: "Following faith in the Lord Jesus Christ, the new convert is commanded by the Word of God to be baptized in water in the Name of the Father and of the Son and of the Holy Spirit.",
    scripture: "Matthew 28:19; Acts 2:38; Mark 16:16; Acts 8:12, 36-38; 10:47-48"
  },
  {
    title: "The Lord's Supper",
    content: "A unique time of communion in the presence of God when the elements of bread and grape juice (the Body and Blood of the Lord Jesus Christ) are taken in remembrance of Jesus' sacrifice on the Cross.",
    scripture: "Matthew 26:26-29; I Corinthians 10:16, 11:23-25"
  },
  {
    title: "Healing of the Sick",
    content: "Healing of the sick is illustrated in the life and ministry of Jesus, and included in the commission of Jesus to His disciples. It is given as a sign, which is to follow believers. It is also a part of Jesus' work on the Cross and one of the gifts of the Spirit.",
    scripture: "Psalm 103:2-3; Isaiah 53:5; Matthew 8:16-17; Mark 16:17-18; Acts 8:6-7; James 5:14-16; I Corinthians 12:9, 28; Romans 11:29"
  },
  {
    title: "God's Will for Provision",
    content: "It is the Father's will for believers to become whole, healthy and successful in all areas of life. But because of the fall, many may not receive the full benefits of God's will while on Earth. That fact, though, should never prevent all believers from seeking the full benefits of Christ's provision in order to better serve others.",
    scripture: "John 3:3-11; II Corinthians 5:17-21; Romans 10:9-10; II Timothy 1:7, 2:11; Philippians 4:7-8; Romans 12:2; Isaiah 26:3; Isaiah 53:4,5; Matthew 8:17; I Peter 2:24; Joshua 1:8; Malachi 3:10-11; Luke 6:38; II Corinthians 9:6-10; Deuteronomy 28:1-14; Psalm 34:10, 84:11; Philippians 4:19"
  },
  {
    title: "Resurrection",
    content: "Jesus Christ was physically resurrected from the dead in a glorified body three days after His death on the cross. In addition, both the saved and the lost will be resurrected; they that are saved to the resurrection of life and they that are lost to the resurrection of eternal damnation.",
    scripture: "Luke 24:16, 36, 39; John 2:19-21, 20:26-28, 21:4; Acts 24:15; I Corinthians 15:42, 44; Philippians 1:21-23, 3:21"
  },
  {
    title: "Heaven",
    content: "Heaven is the eternal dwelling place for all believers in the Gospel of Jesus Christ.",
    scripture: "Matthew 5:3, 12, 20, 6:20, 19:21, 25:34; John 17:24; II Corinthians 5:1; Hebrews 11:16; I Peter 1:4"
  },
  {
    title: "Hell",
    content: "After living one life on earth, the unbelievers will be judged by God and sent to Hell where they will be eternally tormented with the Devil and the Fallen Angels.",
    scripture: "Matthew 25:41; Mark 9:43-48; Hebrews 9:27; Revelation 14:9-11, 20:12-15, 21:8"
  },
  {
    title: "Second Coming",
    content: "Jesus Christ will physically and visibly return to earth for the second time to establish His Kingdom. This will occur at a date undisclosed by the Scriptures.",
    scripture: "Matthew 24:30, 26:63-64; Acts 1:9-11; I Thessalonians 4:15-17; II Thessalonians 1:7-8; Revelation 1:7"
  }
];

export default function BeliefsPage() {
  return (
    <>
      {/* Hero Section */}
      <section className="relative pt-32 pb-16 bg-bg">
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-1/4 right-1/4 w-96 h-96 bg-gold/5 rounded-full blur-3xl" />
        </div>
        
        <div className="relative container-site">
          <Link 
            href="/about" 
            className="inline-flex items-center gap-2 text-text-secondary hover:text-gold transition-colors mb-8"
          >
            <ChevronLeft className="w-4 h-4" />
            Back to About
          </Link>
          
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="max-w-3xl"
          >
            <div className="flex items-center gap-4 mb-6">
              <div className="w-14 h-14 rounded-xl bg-gold/10 flex items-center justify-center">
                <BookOpen className="w-7 h-7 text-gold" />
              </div>
              <div>
                <p className="text-gold uppercase tracking-[0.3em] text-sm">
                  Our Foundation
                </p>
                <h1 className="font-heading text-display-md text-text-primary">
                  What We Believe
                </h1>
              </div>
            </div>
            <p className="text-text-secondary text-body-lg">
              Our beliefs are rooted in the timeless truths of Scripture. These core doctrines guide everything we do as a church and shape how we live out our faith together.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Beliefs List */}
      <section className="section bg-bg-secondary">
        <div className="container-site">
          <div className="max-w-4xl mx-auto space-y-6">
            {beliefs.map((belief, index) => (
              <motion.div
                key={belief.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.05 }}
                className="card"
              >
                <h3 className="font-heading text-heading-lg text-gold mb-3">
                  {belief.title}
                </h3>
                <p className="text-text-primary mb-4">
                  {belief.content}
                </p>
                <p className="text-text-muted text-sm italic">
                  {belief.scripture}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="section bg-bg">
        <div className="container-site text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <h2 className="font-heading text-display-sm text-text-primary mb-4">
              Have Questions?
            </h2>
            <p className="text-text-secondary max-w-2xl mx-auto mb-8">
              We'd love to talk with you about our beliefs and answer any questions you might have.
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <Link href="/visit" className="btn-primary">
                Plan a Visit
              </Link>
              <Link href="/about" className="btn-secondary">
                Learn More About Us
              </Link>
            </div>
          </motion.div>
        </div>
      </section>
    </>
  );
}
